export const GET_NETFLIX_ORI ='GET_NETFLIX_ORI'
export const GET_NETFLIX_TREND ='GET_NETFLIX_TREND'
export const GET_NETFLIX_TOP_RATE ='GET_NETFLIX_TOP_RATE'
export const GET_NETFLIX_COMEMING_UP ='GET_NETFLIX_COMEMING_UP'